version: '3'

services:
#  db:
#    build: db
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./db:/code/db

  app:
    build: app
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
#    depends_on:
#      - db

  frontend:
    build: front
    ports:
      - "8501:8501"
    volumes:
      - ./front:/code/front
    depends_on:
      - app